### ISSUE TITLE
拉扯扩展出来的view可以控制数量？

### ISSUE THREAD

**Issue by wudailaoda** [liuzhiyi1992/ZYThumbnailTableView#1]
看见demo中下面扩展的view是用来做发言提交的，如果我暂时仅需要扩张顶端view作为工具栏，我可以取消底部扩展view的手势吗

**Comment by liuzhiyi1992** [comment]
不需要bottom拓展view的话，只需不设置createBottomExpansionViewBlock即可，topExpansionView同理
