### ISSUE TITLE
Xcode 7.3下报错，我已经download了 分支Xcode7.3Handle

### ISSUE THREAD

**Issue by shenAlexy** [liuzhiyi1992/ZYThumbnailTableView#10]
还是报错，我已经下载了分支Xcode7.3Handle，但是还出现像他们issure那样的报错！

**Comment by liuzhiyi1992** [comment]
是down还是clone？可否将报错信息帖上来呢

**Comment by shenAlexy** [comment]
是down，我确定!

/Users/shenguanhua/Downloads/ZYThumbnailTableView-Xcode7.3-Handle/Pods/ZYThumbnailTableView/ZYThumbnailTableView/Classes/Swift/ZYThumbnailTableViewController.swift:157:74:
warning: use of string literal for Objective-C selectors is deprecated; use
'#selector' instead

```
    NSNotificationCenter.defaultCenter().addObserver(self, selector:
```

"dismissPreview", name: NOTIFY_NAME_DISMISS_PREVIEW, object: nil)

^~~~~~~~~~~~~~~~

#selector(ZYThumbnailTableViewController.dismissPreview)

/Users/shenguanhua/Downloads/ZYThumbnailTableView-Xcode7.3-Handle/Pods/ZYThumbnailTableView/ZYThumbnailTableView/Classes/Swift/ZYThumbnailTableViewController.swift:291:71:
warning: use of string literal for Objective-C selectors is deprecated; use
'#selector' instead

```
    let tapGesture = UITapGestureRecognizer(target: self, action:
```

"tapPreviewCover:")

^~~~~~~~~~~~~~~~~~

#selector(ZYThumbnailTableViewController.tapPreviewCover(_:))

/Users/shenguanhua/Downloads/ZYThumbnailTableView-Xcode7.3-Handle/Pods/ZYThumbnailTableView/ZYThumbnailTableView/Classes/Swift/ZYThumbnailTableViewController.swift:307:71:
warning: use of string literal for Objective-C selectors is deprecated; use
'#selector' instead

```
    let panGesture = UIPanGestureRecognizer(target: self, action:
```

"panThumbnailView:")

^~~~~~~~~~~~~~~~~~~

#selector(ZYThumbnailTableViewController.panThumbnailView(_:))

/Users/shenguanhua/Downloads/ZYThumbnailTableView-Xcode7.3-Handle/Pods/ZYThumbnailTableView/ZYThumbnailTableView/Classes/Swift/ZYThumbnailTableViewController.swift:532:52:
warning: 'init()' is deprecated: init() will be removed in Swift 3.  Use
`nil` instead

```
    var pixelBuffer = UnsafeMutablePointer<Void>()

                                               ^
```

/Users/shenguanhua/Downloads/ZYThumbnailTableView-Xcode7.3-Handle/Pods/ZYThumbnailTableView/ZYThumbnailTableView/Classes/Swift/ZYThumbnailTableViewController.swift:605:36:
warning: use of string literal for Objective-C selectors is deprecated; use
'#selector' instead

```
    if
```

self.respondsToSelector("drawViewHierarchyInRect:afterScreenUpdates:") {

^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

#selector(UIView.drawViewHierarchyInRect(_:afterScreenUpdates:))

0  swift                    0x000000010aff24eb
llvm::sys::PrintStackTrace(llvm::raw_ostream&) + 43

1  swift                    0x000000010aff17d6
llvm::sys::RunSignalHandlers() + 70

2  swift                    0x000000010aff2b4f SignalHandler(int) + 287

3  libsystem_platform.dylib 0x00007fff83af6eaa _sigtramp + 26

4  libsystem_platform.dylib 0x0000000000000020 _sigtramp + 2085654928

5  swift                    0x0000000108f906fa (anonymous
namespace)::TranslateArguments::translateAndExplodeOutOf(swift::Lowering::AbstractionPattern,
swift::CanTypeWrapperswift::TupleType,
swift::Lowering::AbstractionPattern,
swift::CanTypeWrapperswift::TupleType, swift::Lowering::ManagedValue) +
122

6  swift                    0x0000000108f8cd7d (anonymous
namespace)::TranslateArguments::translate(swift::Lowering::AbstractionPattern,
swift::CanType, swift::Lowering::AbstractionPattern, swift::CanType) + 1053

7  swift                    0x0000000108f8cabd (anonymous
namespace)::TranslateArguments::translate(swift::Lowering::AbstractionPattern,
swift::CanType, swift::Lowering::AbstractionPattern, swift::CanType) + 349

8  swift                    0x0000000108f8f6ad
createThunk(swift::Lowering::SILGenFunction&, swift::SILLocation,
swift::Lowering::ManagedValue, swift::Lowering::AbstractionPattern,
swift::CanTypeWrapperswift::AnyFunctionType,
swift::Lowering::AbstractionPattern,
swift::CanTypeWrapperswift::AnyFunctionType,
swift::Lowering::TypeLowering const&) + 1261

9  swift                    0x0000000108f8a8bb (anonymous
namespace)::Transform::transform(swift::Lowering::ManagedValue,
swift::Lowering::AbstractionPattern, swift::CanType,
swift::Lowering::AbstractionPattern, swift::CanType,
swift::Lowering::SGFContext) + 1675

10 swift                    0x0000000108f8a21e
swift::Lowering::SILGenFunction::emitTransformedValue(swift::SILLocation,
swift::Lowering::ManagedValue, swift::CanType, swift::CanType,
swift::Lowering::SGFContext) + 494

11 swift                    0x0000000108f5fe67 swift::ASTVisitor<(anonymous
namespace)::RValueEmitter, swift::Lowering::RValue, void, void, void, void,
void, swift::Lowering::SGFContext>::visit(swift::Expr*,
swift::Lowering::SGFContext) + 26631

12 swift                    0x0000000108f55a86
swift::Lowering::SILGenFunction::emitRValue(swift::Expr*,
swift::Lowering::SGFContext) + 22

13 swift                    0x0000000108f9b61a
swift::Lowering::SILGenFunction::emitReturnExpr(swift::SILLocation,
swift::Expr*) + 378

14 swift                    0x0000000108f98776 swift::ASTVisitor<(anonymous
namespace)::StmtEmitter, void, void, void, void, void,
void>::visit(swift::Stmt*) + 166

15 swift                    0x0000000108f99491 swift::ASTVisitor<(anonymous
namespace)::StmtEmitter, void, void, void, void, void,
void>::visit(swift::Stmt*) + 3521

16 swift                    0x0000000108f986c5
swift::Lowering::SILGenFunction::emitStmt(swift::Stmt*) + 21

17 swift                    0x0000000108f67e8d
swift::Lowering::SILGenFunction::emitClosure(swift::AbstractClosureExpr*) +
221

18 swift                    0x0000000108f1f80c
swift::Lowering::SILGenModule::emitClosure(swift::AbstractClosureExpr*) +
220

19 swift                    0x0000000108f3384c (anonymous
namespace)::SILGenApply::visitAbstractClosureExpr(swift::AbstractClosureExpr*)
- 92

20 swift                    0x0000000108f35622 (anonymous
namespace)::SILGenApply::visitApplyExpr(swift::ApplyExpr*) + 5186

21 swift                    0x0000000108f28bb5
prepareApplyExpr(swift::Lowering::SILGenFunction&, swift::Expr*) + 165

22 swift                    0x0000000108f28acf
swift::Lowering::SILGenFunction::emitApplyExpr(swift::Expr*,
swift::Lowering::SGFContext) + 47

23 swift                    0x0000000108f596b7 swift::ASTVisitor<(anonymous
namespace)::RValueEmitter, swift::Lowering::RValue, void, void, void, void,
void, swift::Lowering::SGFContext>::visit(swift::Expr*,
swift::Lowering::SGFContext) + 87

24 swift                    0x0000000108f559d4
swift::Lowering::SILGenFunction::emitExprInto(swift::Expr_,
swift::Lowering::Initialization_) + 276

25 swift                    0x0000000108f4a306
swift::Lowering::SILGenFunction::emitPatternBinding(swift::PatternBindingDecl*,
unsigned int) + 198

26 swift                    0x0000000108f4a3fd
swift::Lowering::SILGenFunction::visitPatternBindingDecl(swift::PatternBindingDecl*)
- 45

27 swift                    0x0000000108f99519 swift::ASTVisitor<(anonymous
namespace)::StmtEmitter, void, void, void, void, void,
void>::visit(swift::Stmt*) + 3657

28 swift                    0x0000000108f986c5
swift::Lowering::SILGenFunction::emitStmt(swift::Stmt*) + 21

29 swift                    0x0000000108f67d5f
swift::Lowering::SILGenFunction::emitFunction(swift::FuncDecl*) + 303

30 swift                    0x0000000108f1dd61
swift::Lowering::SILGenModule::emitFunction(swift::FuncDecl*) + 1057

31 swift                    0x0000000108f9d808 (anonymous
namespace)::SILGenType::emitType() + 1192

32 swift                    0x0000000108f9d2ee
swift::Lowering::SILGenModule::visitNominalTypeDecl(swift::NominalTypeDecl*)
- 30

33 swift                    0x0000000108f2251b
swift::Lowering::SILGenModule::emitSourceFile(swift::SourceFile*, unsigned
int) + 731

34 swift                    0x0000000108f23069
swift::SILModule::constructSIL(swift::ModuleDecl_, swift::SILOptions&,
swift::FileUnit_, llvm::Optional<unsigned int>, bool, bool) + 793

35 swift                    0x0000000108f234d3
swift::performSILGeneration(swift::FileUnit&, swift::SILOptions&,
llvm::Optional<unsigned int>, bool) + 115

36 swift                    0x0000000108d470d3
performCompile(swift::CompilerInstance&, swift::CompilerInvocation&,
llvm::ArrayRef<char const*>, int&) + 12627

37 swift                    0x0000000108d4341d
frontend_main(llvm::ArrayRef<char const*>, char const_, void_) + 2781

38 swift                    0x0000000108d3ee3c main + 1932

39 libdyld.dylib            0x00007fff878245ad start + 1

Stack dump:
1. Program arguments:
   /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift
   -frontend -c -primary-file
   /Users/shenguanhua/Downloads/ZYThumbnailTableView-Xcode7.3-Handle/Pods/ZYThumbnailTableView/ZYThumbnailTableView/Classes/Swift/ZYThumbnailTableViewController.swift
   -target x86_64-apple-ios9.3 -enable-objc-interop -sdk
   /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.3.sdk
   -I
   /Users/shenguanhua/Library/Developer/Xcode/DerivedData/ZYThumbnailTableView-cufgntvdwrscekgzmmqfjhsuczqx/Build/Products/Debug-iphonesimulator
   -F
   /Users/shenguanhua/Library/Developer/Xcode/DerivedData/ZYThumbnailTableView-cufgntvdwrscekgzmmqfjhsuczqx/Build/Products/Debug-iphonesimulator
   -g -import-underlying-module -module-cache-path
   /Users/shenguanhua/Library/Developer/Xcode/DerivedData/ModuleCache -D
   COCOAPODS -serialize-debugging-options -Xcc
   -I/Users/shenguanhua/Library/Developer/Xcode/DerivedData/ZYThumbnailTableView-cufgntvdwrscekgzmmqfjhsuczqx/Build/Intermediates/Pods.build/Debug-iphonesimulator/ZYThumbnailTableView.build/swift-overrides.hmap
   -Xcc -iquote -Xcc
   /Users/shenguanhua/Library/Developer/Xcode/DerivedData/ZYThumbnailTableView-cufgntvdwrscekgzmmqfjhsuczqx/Build/Intermediates/Pods.build/Debug-iphonesimulator/ZYThumbnailTableView.build/ZYThumbnailTableView-generated-files.hmap
   -Xcc
   -I/Users/shenguanhua/Library/Developer/Xcode/DerivedData/ZYThumbnailTableView-cufgntvdwrscekgzmmqfjhsuczqx/Build/Intermediates/Pods.build/Debug-iphonesimulator/ZYThumbnailTableView.build/ZYThumbnailTableView-own-target-headers.hmap
   -Xcc
   -I/Users/shenguanhua/Library/Developer/Xcode/DerivedData/ZYThumbnailTableView-cufgntvdwrscekgzmmqfjhsuczqx/Build/Intermediates/Pods.build/Debug-iphonesimulator/ZYThumbnailTableView.build/ZYThumbnailTableView-all-non-framework-target-headers.hmap
   -Xcc -ivfsoverlay -Xcc
   /Users/shenguanhua/Library/Developer/Xcode/DerivedData/ZYThumbnailTableView-cufgntvdwrscekgzmmqfjhsuczqx/Build/Intermediates/Pods.build/all-product-headers.yaml
   -Xcc -iquote -Xcc
   /Users/shenguanhua/Library/Developer/Xcode/DerivedData/ZYThumbnailTableView-cufgntvdwrscekgzmmqfjhsuczqx/Build/Intermediates/Pods.build/Debug-iphonesimulator/ZYThumbnailTableView.build/ZYThumbnailTableView-project-headers.hmap
   -Xcc
   -I/Users/shenguanhua/Library/Developer/Xcode/DerivedData/ZYThumbnailTableView-cufgntvdwrscekgzmmqfjhsuczqx/Build/Products/Debug-iphonesimulator/include
   -Xcc
   -I/Users/shenguanhua/Downloads/ZYThumbnailTableView-Xcode7.3-Handle/Pods/Headers/Private
   -Xcc
   -I/Users/shenguanhua/Downloads/ZYThumbnailTableView-Xcode7.3-Handle/Pods/Headers/Private/ZYThumbnailTableView
   -Xcc
   -I/Users/shenguanhua/Downloads/ZYThumbnailTableView-Xcode7.3-Handle/Pods/Headers/Public
   -Xcc
   -I/Users/shenguanhua/Library/Developer/Xcode/DerivedData/ZYThumbnailTableView-cufgntvdwrscekgzmmqfjhsuczqx/Build/Intermediates/Pods.build/Debug-iphonesimulator/ZYThumbnailTableView.build/DerivedSources/x86_64
   -Xcc
   -I/Users/shenguanhua/Library/Developer/Xcode/DerivedData/ZYThumbnailTableView-cufgntvdwrscekgzmmqfjhsuczqx/Build/Intermediates/Pods.build/Debug-iphonesimulator/ZYThumbnailTableView.build/DerivedSources
   -Xcc -DDEBUG=1 -Xcc -DCOCOAPODS=1 -Xcc -ivfsoverlay -Xcc
   /Users/shenguanhua/Library/Developer/Xcode/DerivedData/ZYThumbnailTableView-cufgntvdwrscekgzmmqfjhsuczqx/Build/Intermediates/Pods.build/Debug-iphonesimulator/ZYThumbnailTableView.build/unextended-module-overlay.yaml
   -Xcc
   -working-directory/Users/shenguanhua/Downloads/ZYThumbnailTableView-Xcode7.3-Handle/Pods
   -emit-module-doc-path
   /Users/shenguanhua/Library/Developer/Xcode/DerivedData/ZYThumbnailTableView-cufgntvdwrscekgzmmqfjhsuczqx/Build/Intermediates/Pods.build/Debug-iphonesimulator/ZYThumbnailTableView.build/Objects-normal/x86_64/ZYThumbnailTableViewController~partial.swiftdoc
   -Onone -parse-as-library -module-name ZYThumbnailTableView
   -emit-module-path
   /Users/shenguanhua/Library/Developer/Xcode/DerivedData/ZYThumbnailTableView-cufgntvdwrscekgzmmqfjhsuczqx/Build/Intermediates/Pods.build/Debug-iphonesimulator/ZYThumbnailTableView.build/Objects-normal/x86_64/ZYThumbnailTableViewController~partial.swiftmodule
   -serialize-diagnostics-path
   /Users/shenguanhua/Library/Developer/Xcode/DerivedData/ZYThumbnailTableView-cufgntvdwrscekgzmmqfjhsuczqx/Build/Intermediates/Pods.build/Debug-iphonesimulator/ZYThumbnailTableView.build/Objects-normal/x86_64/ZYThumbnailTableViewController.dia
   -emit-dependencies-path
   /Users/shenguanhua/Library/Developer/Xcode/DerivedData/ZYThumbnailTableView-cufgntvdwrscekgzmmqfjhsuczqx/Build/Intermediates/Pods.build/Debug-iphonesimulator/ZYThumbnailTableView.build/Objects-normal/x86_64/ZYThumbnailTableViewController.d
   -emit-reference-dependencies-path
   /Users/shenguanhua/Library/Developer/Xcode/DerivedData/ZYThumbnailTableView-cufgntvdwrscekgzmmqfjhsuczqx/Build/Intermediates/Pods.build/Debug-iphonesimulator/ZYThumbnailTableView.build/Objects-normal/x86_64/ZYThumbnailTableViewController.swiftdeps
   -o
   /Users/shenguanhua/Library/Developer/Xcode/DerivedData/ZYThumbnailTableView-cufgntvdwrscekgzmmqfjhsuczqx/Build/Intermediates/Pods.build/Debug-iphonesimulator/ZYThumbnailTableView.build/Objects-normal/x86_64/ZYThumbnailTableViewController.o
2. While emitting SIL for getter for createTopExpansionViewBlock at
   /Users/shenguanhua/Downloads/ZYThumbnailTableView-Xcode7.3-Handle/Pods/ZYThumbnailTableView/ZYThumbnailTableView/Classes/Swift/ZYThumbnailTableViewController.swift:120:14
3. While silgen closureexpr SIL function
   @_TFFC20ZYThumbnailTableView30ZYThumbnailTableViewControllerg27createTopExpansionViewBlockFT9indexPathCSo11NSIndexPath_GSqCSo6UIView_U_FT_FT9indexPathS1__GSqS2__
   for expression at
   [/Users/shenguanhua/Downloads/ZYThumbnailTableView-Xcode7.3-Handle/Pods/ZYThumbnailTableView/ZYThumbnailTableView/Classes/Swift/ZYThumbnailTableViewController.swift:120:73
4. line:125:5] RangeText="{
   
   ```
   return {
   
       print("WARNNING: You have no configure the
   ```
   
   createTopExpansionViewBlock")
   
   ```
       return nil
   
   }
   ```
   
   }"
5. While emitting reabstraction thunk in SIL function
   @_TTRXFo__oGSqCSo6UIView__XFo_oCSo11NSIndexPath_oGSqS___

2016-05-04 18:49 GMT+08:00 liuzhiyi1992 notifications@github.com:

**Comment by liuzhiyi1992** [comment]
[ZYThumbnailTableView-Xcode7.3-Handle (1).zip](https://github.com/liuzhiyi1992/ZYThumbnailTableView/files/250017/ZYThumbnailTableView-Xcode7.3-Handle.1.zip)

朋友你这个是Xcode7.3之前的代码，可能你分支没切换成功，我传给你试试。
