### ISSUE TITLE
在Swift工程中用pod引入这个库，然后在文件了import提示找不到这个库

### ISSUE THREAD

**Issue by onegaop** [liuzhiyi1992/ZYThumbnailTableView#12]
其他纯Swift的库是没问题的，单单楼主这个库不行，望指导一下

**Comment by liuzhiyi1992** [comment]
不太明白朋友的意思，swift工程应该不需要#import文件的吧？不是应该直接可以使用吗？

**Comment by onegaop** [comment]
我是用cococapods引入的额，都要import,打开的是xcworkspace，不在一个工程文件夹类似这样的
![2](https://cloud.githubusercontent.com/assets/13845910/17481555/6181002c-5db0-11e6-8438-b8b7c8deccfd.jpg)

**Comment by liuzhiyi1992** [comment]
ok我明天看下再答复你

**Comment by liuzhiyi1992** [comment]
这个问题的确存在，好像pod打包的Module中完全丢失了源代码，暂时还没找到解决办法

**Comment by liuzhiyi1992** [comment]
@EagleKing  问题基本解决了，更新pod1.0.4试试  : )

**Comment by AgoniNemo** [comment]
@liuzhiyi1992 你好我也遇到这个问题，请问你是怎么解决的
