### ISSUE TITLE
Demo在Xcode7.3环境下打不开

### ISSUE THREAD

**Issue by OYcedar** [liuzhiyi1992/ZYThumbnailTableView#2]
给出的错误提示为：Command failed due to signal: Segmentation fault: 11

**Comment by liuzhiyi1992** [comment]
晚上找个时间更新xcode看看，哈哈真不好意思

**Comment by liuzhiyi1992** [comment]
问题已经解决，如果已更新Xcode7.3，下载分支Xcode7.3-Handle即可。
这个问题据RxSwift大神说是xcode升级对swift2.2支持的bug，后续再等待苹果的说法。
