### ISSUE TITLE
Carthage compatible.

### ISSUE THREAD

**Issue by Dershowitz011** [liuzhiyi1992/ZYThumbnailTableView#5]
Try making this repo Carthage compatible. Thanks.

**Comment by liuzhiyi1992** [comment]
I am very willing to do that, but Carthage unsupport to use bridging headers, and ZYThumbnailTableView were mixture of swift and objc.🤔

**Comment by Dershowitz011** [comment]
https://github.com/SVProgressHUD/SVProgressHUD/issues/509 !! Take a look at this! @liuzhiyi1992

**Comment by Dershowitz011** [comment]
https://github.com/Dershowitz011/ZYYT .. I've made this Carthage Compatible. Let me know if you're ok with it and if you're ok with it let me know if it works fine. @liuzhiyi1992

**Comment by liuzhiyi1992** [comment]
I'm very sorry a little busy recently，i have deploy ZYTT.framework to my project, create a ZYThumbnailTableView object already, but can not access the property in it. 

like:
zyVC.tableViewCellReuseId
zyVC.tableViewCellHeight
can not access and assign both

something i have forgotten?

thanks

**Comment by Dershowitz011** [comment]
Let me check. You check too and create a pull request in case we've both gone wrong somewhere and this is only  for the xcode 7.3 updated version.
