### ISSUE TITLE
Hey, just wanna ask that how did you make the gif in a phone frame?

### ISSUE THREAD

**Issue by Nightonke** [liuzhiyi1992/ZYThumbnailTableView#6]
Hello. How did you make the gif in the iphone like that? From a website or something else?

**Comment by liuzhiyi1992** [comment]
Record the screen by Quite Time, and mix mp4&phone pic by Adobe AE

**Comment by Nightonke** [comment]
Thanks.

**Comment by liuzhiyi1992** [comment]
You're welcome, I remember that use 'CC Power Pin' in AE to distorted the video, and adjust youself.
