### ISSUE TITLE
Xcode7.3运行出错

### ISSUE THREAD

**Issue by onegaop** [liuzhiyi1992/ZYThumbnailTableView#8]
Command failed due to signal: Segmentation fault: 11
运行不了

**Comment by liuzhiyi1992** [comment]
Xcode7.3以上请使用  分支Xcode7.3Handle哦 : )

**Comment by onegaop** [comment]
就是你的handle版本，还是这样额

**Comment by liuzhiyi1992** [comment]
方便把报错的图贴出来吗？qq截图直接拖进输入框就可以了，感谢

**Comment by onegaop** [comment]
CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
    cd /Users/eagle/Desktop/githubCode/ZYThumbnailTableView
    export DEVELOPER_DIR=/Applications/Xcode.app/Contents/Developer
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    export SDKROOT=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.3.sdk
    export TOOLCHAINS=com.apple.dt.toolchain.iOS9_3
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc -incremental -module-name ZYThumbnailTableView -Onone -sdk /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.3.sdk -target x86_64-apple-ios8.0 -g -module-cache-path /Users/eagle/Library/Developer/Xcode/DerivedData/ModuleCache -Xfrontend -serialize-debugging-options -enable-testing -I /Users/eagle/Library/Developer/Xcode/DerivedData/ZYThumbnailTableView-bydowewwngshsrbcsbokhtfgsngj/Build/Products/Debug-iphonesimulator -F /Users/eagle/Library/Developer/Xcode/DerivedData/ZYThumbnailTableView-bydowewwngshsrbcsbokhtfgsngj/Build/Products/Debug-iphonesimulator -c -j4 /Users/eagle/Desktop/githubCode/ZYThumbnailTableView/ZYThumbnailTableView/ViewController.swift /Users/eagle/Desktop/githubCode/ZYThumbnailTableView/ZYThumbnailTableView/DiyViews/DIYTableViewCell.swift /Users/eagle/Desktop/githubCode/ZYThumbnailTableView/ZYThumbnailTableView/Classes/Swift/ZYThumbnailTableViewController.swift /Users/eagle/Desktop/githubCode/ZYThumbnailTableView/ZYThumbnailTableView/DiyViews/BottomView.swift /Users/eagle/Desktop/githubCode/ZYThumbnailTableView/ZYThumbnailTableView/DiyViews/TopView.swift /Users/eagle/Desktop/githubCode/ZYThumbnailTableView/ZYThumbnailTableView/AppDelegate.swift -output-file-map /Users/eagle/Library/Developer/Xcode/DerivedData/ZYThumbnailTableView-bydowewwngshsrbcsbokhtfgsngj/Build/Intermediates/ZYThumbnailTableView.build/Debug-iphonesimulator/ZYThumbnailTableView.build/Objects-normal/x86_64/ZYThumbnailTableView-OutputFileMap.json -parseable-output -serialize-diagnostics -emit-dependencies -emit-module -emit-module-path /Users/eagle/Library/Developer/Xcode/DerivedData/ZYThumbnailTableView-bydowewwngshsrbcsbokhtfgsngj/Build/Intermediates/ZYThumbnailTableView.build/Debug-iphonesimulator/ZYThumbnailTableView.build/Objects-normal/x86_64/ZYThumbnailTableView.swiftmodule -Xcc -I/Users/eagle/Library/Developer/Xcode/DerivedData/ZYThumbnailTableView-bydowewwngshsrbcsbokhtfgsngj/Build/Intermediates/ZYThumbnailTableView.build/Debug-iphonesimulator/ZYThumbnailTableView.build/swift-overrides.hmap -Xcc -iquote -Xcc /Users/eagle/Library/Developer/Xcode/DerivedData/ZYThumbnailTableView-bydowewwngshsrbcsbokhtfgsngj/Build/Intermediates/ZYThumbnailTableView.build/Debug-iphonesimulator/ZYThumbnailTableView.build/ZYThumbnailTableView-generated-files.hmap -Xcc -I/Users/eagle/Library/Developer/Xcode/DerivedData/ZYThumbnailTableView-bydowewwngshsrbcsbokhtfgsngj/Build/Intermediates/ZYThumbnailTableView.build/Debug-iphonesimulator/ZYThumbnailTableView.build/ZYThumbnailTableView-own-target-headers.hmap -Xcc -I/Users/eagle/Library/Developer/Xcode/DerivedData/ZYThumbnailTableView-bydowewwngshsrbcsbokhtfgsngj/Build/Intermediates/ZYThumbnailTableView.build/Debug-iphonesimulator/ZYThumbnailTableView.build/ZYThumbnailTableView-all-target-headers.hmap -Xcc -iquote -Xcc /Users/eagle/Library/Developer/Xcode/DerivedData/ZYThumbnailTableView-bydowewwngshsrbcsbokhtfgsngj/Build/Intermediates/ZYThumbnailTableView.build/Debug-iphonesimulator/ZYThumbnailTableView.build/ZYThumbnailTableView-project-headers.hmap -Xcc -I/Users/eagle/Library/Developer/Xcode/DerivedData/ZYThumbnailTableView-bydowewwngshsrbcsbokhtfgsngj/Build/Products/Debug-iphonesimulator/include -Xcc -I/Users/eagle/Library/Developer/Xcode/DerivedData/ZYThumbnailTableView-bydowewwngshsrbcsbokhtfgsngj/Build/Intermediates/ZYThumbnailTableView.build/Debug-iphonesimulator/ZYThumbnailTableView.build/DerivedSources/x86_64 -Xcc -I/Users/eagle/Library/Developer/Xcode/DerivedData/ZYThumbnailTableView-bydowewwngshsrbcsbokhtfgsngj/Build/Intermediates/ZYThumbnailTableView.build/Debug-iphonesimulator/ZYThumbnailTableView.build/DerivedSources -Xcc -DDEBUG=1 -emit-objc-header -emit-objc-header-path /Users/eagle/Library/Developer/Xcode/DerivedData/ZYThumbnailTableView-bydowewwngshsrbcsbokhtfgsngj/Build/Intermediates/ZYThumbnailTableView.build/Debug-iphonesimulator/ZYThumbnailTableView.build/Objects-normal/x86_64/ZYThumbnailTableView-Swift.h -import-objc-header /Users/eagle/Desktop/githubCode/ZYThumbnailTableView/ZYThumbnailTableView/Classes/ZYThumbnailTableView-Bridging-Header.h -Xcc -working-directory/Users/eagle/Desktop/githubCode/ZYThumbnailTableView

<unknown>:0: error: unable to execute command: Segmentation fault: 11
<unknown>:0: error: compile command failed due to signal (use -v to see invocation)

**Comment by onegaop** [comment]
![86d2a879-6bc2-4798-9a59-3d333822b878](https://cloud.githubusercontent.com/assets/13845910/14629948/c04cabd6-063c-11e6-9ec5-a8f1af21bda8.png)

**Comment by liuzhiyi1992** [comment]
朋友这个应该是master分支，不是Handler分支，再down一次看看

**Comment by onegaop** [comment]
额，什么情况，之前我是clone的项目都不行，难道clone错了。。download zip是可以的

**Comment by liuzhiyi1992** [comment]
一般clone只能clone到master，可以使用git branch -a查看全部分支，然后使用git checkout -t来checkout需要的分支

**Comment by onegaop** [comment]
thank you:)
