### ISSUE TITLE
Errors Xcode 7.3

### ISSUE THREAD

**Issue by Ged2323** [liuzhiyi1992/ZYThumbnailTableView#9]
Hi I just tried to run this in Xcode 7.3 and I got these errors.

Thanks in advance for your help.

Command /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc failed with exit code 1

Command failed due to signal: Segmentation fault: 11

Command /usr/bin/ditto failed with exit code 1

**Comment by liuzhiyi1992** [comment]
In Xcode7.3-Handle branch solve this problem
